apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: bitnami/mongodb
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 13.x.x
  values:
    auth:
      enabled: true
      username: admin
      password: p@ss1234
      database: mydb
