apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: prod-apps
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./flux/workloads
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default
