apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prod-apps
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./flux/workloads
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system          # This must match your GitRepository name
    namespace: flux-system
  targetNamespace: default     # where your apps will deploy
  timeout: 2m
