apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: service2
  namespace: flux-system
spec:
  interval: 1m
  path: ../../base/service2
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default
