apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
        - name: service2
          image: us-central1-docker.pkg.dev/psychic-etching-466000-n9/my-repo/service2:latest
          ports:
            - containerPort: 3000
