apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: bitnami/mongodb
      version: 13.x.x
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: mongodb-values
