apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/ragavanvp/gke-cicd-app
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include infra/flux/clusters/prod
    !/infra/flux/clusters/prod
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infra/flux/clusters/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client

