# gke-cicd-app/infra/flux/clusters/prod/flux-system/gotk-sync.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 1m
  path: ./infra/flux/clusters/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

